name: Discord notification

on:
  push:
    branches:
      - main

jobs: 
  discord_notification: 
    runs-on: ubuntu-20.04
    steps:
      - name: Notification
        uses: sebastianpopp/discord-action@releases/v2
        if: ${{ success() }}
        with:
            webhook: ${{ secrets.DISCORD_WEBHOOK_KEY }}
            message: to https://full-stack-open-pokedex-icy-smoke-5647.fly.dev/ by ${{ github.event.commits.committer.name }}

      - name: Test Error
        uses: sebastianpopp/discord-action@releases/v2
        if: ${{ failure() }}
        with:
            webhook: ${{ secrets.DISCORD_WEBHOOK_KEY }}
            message: commit by ${{ github.event.commits.committer.name }} broke the build :(
            
            

      
