name: Discord notification

on:
  push:
    branches:
      - main

jobs: 
  discord_notification: 
    runs-on: ubuntu-20.04
    steps:
      - name: Notification
        uses: BubbleProd/discord-webhook-notify@v2.0.1
        if: ${{ success() }}
        with:
            severity: info
            description: to https://full-stack-open-pokedex-icy-smoke-5647.fly.dev/ by ${{ github.repository_owner }}
            text: A new version of Pokedex deployed
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Error
        uses: BubbleProd/discord-webhook-notify@v2.0.1
        if: ${{ failure() }}
        with:
            severity: error
            text: Build failed
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      
