name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages contains skip
        env:
          COMMIT_MESSAGES: ${{ toJson(contains(join(github.event.commits.*.message), '#skip')) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages contains skip if equal to false
        env:
          COMMIT_MESSAGES: ${{ toJson(contains(join(github.event.commits.*.message), '#skip') == 'false') }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages contains skip if equal to 'false'
        env:
          COMMIT_MESSAGES: ${{ toJson(contains(join(github.event.commits.*.message), '#skip') == false) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages doesn't contain skip 
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event_name == 'push' && contains(join(github.event.commits.*.message), '#skip') == 'false') }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit link
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.head_commit.url ) }}
        run: echo "$COMMIT_MESSAGES"
      - name: sha
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.head_commit.sha ) }}
        run: echo "$COMMIT_MESSAGES"
      - name: repository url
        env:
          COMMIT_MESSAGES: ${{ toJson(github.repositoryUrl ) }}
        run: echo "$COMMIT_MESSAGES"
  